dist: xenial
language: python
os:
  - linux
  - osx
python:
  - "3.5"
  - "3.6"
  - "3.7"
install:
  - pip install .
# command to run tests
script:
  - pytest escpy/test/test_*.py
notifications:
  email:
    - singularitti@outlook.com
