language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8-dev" # 3.8 development branch
# command to run tests
script:
  - pytest escpy/test/test_*.py
notifications:
  email:
    - singularitti@outlook.com
